using System;
using System.Collections.Generic;
using Macros.Commands;
using Macros.Engine.Triggers;
using Xunit;

namespace Macros.Tests.Commands;

/// <summary>
/// Tests for <see cref="TriggerHeaderRewriter"/>, the pure string transformation that
/// rewrites the leading <c>// @trigger ...</c> directive block of a <c>.csx</c> file
/// without touching the body.
/// </summary>
public sealed class TriggerHeaderRewriterTests
{
    private static readonly TriggerBinding _vsEvent =
        new(TriggerKind.VsEvent, "Build.SolutionBuildDone");
    private static readonly TriggerBinding _vsEventWithFilter =
        new(TriggerKind.VsEvent, "Document.Saved",
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["filename"] = "*.cs",
            });
    private static readonly TriggerBinding _beforeSave =
        new(TriggerKind.BeforeCommand, "File.Save");

    [Fact]
    public void Rewrite_NoExistingTriggers_AddsNewDirectiveAtEndOfHeader()
    {
        var src = string.Join("\n", new[]
        {
            "// Macro: foo",
            "// Generated by Macros — edit freely.",
            "",
            "using System;",
            "Console.WriteLine(\"hi\");",
            "",
        });

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _vsEvent });

        Assert.Contains("// @trigger Build.SolutionBuildDone", result);
        // Body must still be present unchanged.
        Assert.Contains("using System;\nConsole.WriteLine(\"hi\");\n", result);
        // Directive must appear before "using System;" — i.e., in header.
        var dirIdx = result.IndexOf("// @trigger", StringComparison.Ordinal);
        var usingIdx = result.IndexOf("using System;", StringComparison.Ordinal);
        Assert.True(dirIdx < usingIdx);
    }

    [Fact]
    public void Rewrite_TwoExistingTriggers_RemoveAll_HeaderHasNoDirectives()
    {
        var src = string.Join("\n", new[]
        {
            "// Macro: foo",
            "// @trigger Build.SolutionBuildDone",
            "// @trigger BeforeCommand File.Save",
            "",
            "using System;",
        });

        var result = TriggerHeaderRewriter.Rewrite(src, Array.Empty<TriggerBinding>());

        Assert.DoesNotContain("@trigger", result);
        Assert.Contains("// Macro: foo", result);
        Assert.Contains("using System;", result);
    }

    [Fact]
    public void Rewrite_OneExistingReplacedWithTwoNew_OldRemoved_NewInDeclaredOrder()
    {
        var src = string.Join("\n", new[]
        {
            "// Macro: foo",
            "// @trigger Build.SolutionBuildDone",
            "",
            "using System;",
        });

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _beforeSave, _vsEventWithFilter });

        Assert.DoesNotContain("Build.SolutionBuildDone", result);
        var idxBefore = result.IndexOf("// @trigger BeforeCommand File.Save", StringComparison.Ordinal);
        var idxAfter = result.IndexOf("// @trigger Document.Saved when filename=*.cs", StringComparison.Ordinal);
        Assert.True(idxBefore >= 0);
        Assert.True(idxAfter >= 0);
        Assert.True(idxBefore < idxAfter);
    }

    [Fact]
    public void Rewrite_BodyIsPreservedByteForByte()
    {
        const string body =
            "using System;\n" +
            "// inline comment that mentions @trigger but is in the body\n" +
            "Console.WriteLine(\"hello\");\n" +
            "// trailing comment\n";

        var src = "// Macro: foo\n// @trigger Build.SolutionBuildDone\n\n" + body;

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _beforeSave });

        // The body must remain identical, including all interior @trigger-mentions.
        Assert.EndsWith(body, result);
    }

    [Fact]
    public void Rewrite_PreservesLfLineEndings()
    {
        var src = "// Macro: foo\n\nusing System;\n";

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _vsEvent });

        Assert.DoesNotContain("\r", result);
    }

    [Fact]
    public void Rewrite_PreservesCrlfLineEndings()
    {
        var src = "// Macro: foo\r\n\r\nusing System;\r\n";

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _vsEvent });

        // Every \n in the result should be preceded by \r (i.e., file is uniformly CRLF).
        for (int i = 0; i < result.Length; i++)
        {
            if (result[i] == '\n')
            {
                Assert.True(i > 0 && result[i - 1] == '\r',
                    $"Bare \\n at position {i} broke CRLF preservation: {result.Substring(Math.Max(0, i - 5), Math.Min(10, result.Length - i))}");
            }
        }
    }

    [Fact]
    public void Rewrite_IsIdempotent()
    {
        var src = "// Macro: foo\n// Generated by Macros — edit freely.\n\nusing System;\n";
        var bindings = new[] { _vsEvent, _beforeSave };

        var once = TriggerHeaderRewriter.Rewrite(src, bindings);
        var twice = TriggerHeaderRewriter.Rewrite(once, bindings);

        Assert.Equal(once, twice);
    }

    [Fact]
    public void Rewrite_EmptySource_EmptyBindings_ReturnsEmpty()
    {
        Assert.Equal(string.Empty, TriggerHeaderRewriter.Rewrite(string.Empty, Array.Empty<TriggerBinding>()));
    }

    [Fact]
    public void Rewrite_NullSource_ReturnsBindingsOnly()
    {
        var result = TriggerHeaderRewriter.Rewrite(null, new[] { _vsEvent });
        Assert.Contains("// @trigger Build.SolutionBuildDone", result);
    }

    [Fact]
    public void Rewrite_HeaderWithExampleLine_DoesNotStripExample()
    {
        // The codegen header includes "// EXAMPLE: // @trigger Build.SolutionBuildDone".
        // After stripping the outer "// ", what remains is "EXAMPLE: // @trigger ..." which
        // does NOT begin with @trigger — the parser ignores it, and so must the rewriter.
        var src = string.Join("\n", new[]
        {
            "// Macro: foo",
            "// EXAMPLE: // @trigger Build.SolutionBuildDone",
            "",
            "using System;",
        });

        var result = TriggerHeaderRewriter.Rewrite(src, Array.Empty<TriggerBinding>());

        Assert.Contains("// EXAMPLE: // @trigger Build.SolutionBuildDone", result);
    }

    [Fact]
    public void Rewrite_RoundTripThroughParser_RecoversBindings()
    {
        var src = "// Macro: foo\n\nusing System;\n";
        var bindings = new[] { _vsEvent, _beforeSave, _vsEventWithFilter };

        var rewritten = TriggerHeaderRewriter.Rewrite(src, bindings);
        var parsed = TriggerDirectiveParser.Parse(rewritten);

        Assert.Equal(bindings.Length, parsed.Count);
        for (int i = 0; i < bindings.Length; i++)
        {
            Assert.Equal(bindings[i], parsed[i]);
        }
    }

    [Fact]
    public void Rewrite_DirectivesAppearAfterLastCommentBeforeBlankSeparator()
    {
        var src = string.Join("\n", new[]
        {
            "// Macro: foo",
            "// Generated by Macros — edit freely.",
            "",
            "using System;",
        });

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _vsEvent });

        // Order: "// Macro" → "// Generated" → "// @trigger" → blank line → "using System;"
        var idxGenerated = result.IndexOf("// Generated", StringComparison.Ordinal);
        var idxTrigger = result.IndexOf("// @trigger", StringComparison.Ordinal);
        var idxBlank = result.IndexOf("\n\n", StringComparison.Ordinal);
        var idxUsing = result.IndexOf("using System;", StringComparison.Ordinal);

        Assert.True(idxGenerated < idxTrigger);
        Assert.True(idxTrigger < idxBlank);
        Assert.True(idxBlank < idxUsing);
    }

    [Fact]
    public void Rewrite_OnlyComments_NoBlankSeparator_AppendsDirectiveAfterLastComment()
    {
        var src = "// Macro: foo\nusing System;\n";

        var result = TriggerHeaderRewriter.Rewrite(src, new[] { _vsEvent });

        Assert.Contains("// Macro: foo\n// @trigger Build.SolutionBuildDone\nusing System;", result);
    }

    [Fact]
    public void Rewrite_ThrowsOnNullBindings()
    {
        Assert.Throws<ArgumentNullException>(() => TriggerHeaderRewriter.Rewrite("// foo\n", null!));
    }
}
