<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Company>Mads Kristensen</Company>
    <Authors>Mads Kristensen</Authors>
    <Product>Macros for Visual Studio</Product>
    <Copyright>Copyright © Mads Kristensen 2026</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Build hygiene -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>NU1701;CS1591</WarningsNotAsErrors>
    <NoWarn>$(NoWarn);CS1591;NU1701;CVSTBLD002</NoWarn>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
