// Macro: Auto-collapse #region blocks on open
// Recorded: 2026-05-02T10:23:08Z
// Steps: 2
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// @trigger Document.Opened
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

// step 1: inspect the opened document for #region directives
var textDocument = DTE.ActiveDocument?.Object("TextDocument") as EnvDTE.TextDocument;
if (textDocument is null)
{
    return;
}

var start = textDocument.StartPoint.CreateEditPoint();
string documentText = start.GetText(textDocument.EndPoint);
if (documentText.IndexOf("#region", StringComparison.Ordinal) < 0)
{
    return;
}

// step 2: collapse outlining once the file is known to contain regions
await ExecuteCommandAsync("Edit.CollapseAllOutlining");
