// Macro: Format on save for C# files only
// Recorded: 2026-05-02T10:23:08Z
// Steps: 2
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// @trigger Document.Saved when filename=*.cs
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

// step 1:skip anything that is not an active C# document
if (Context.CurrentDocument?.Name.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) != true)
{
    return;
}

// step 2: format the saved file and surface a brief confirmation
await ExecuteCommandAsync("Edit.FormatDocument");
await VS.StatusBar.ShowMessageAsync($"Macros: Formatted {Context.CurrentDocument?.Name}");
