// Prompts for an author name and inserts a simple file header at the caret.
#load ".intellisense/Macros.Intellisense.csx"

// step 1:collect a few values for the header
string author = await PromptAsync("Author:", Environment.UserName);
string fileName = Context.CurrentDocument?.Name ?? "NewFile.cs";

// step 2: insert a multi-line header at the current caret position
var header = $@"// ------------------------------------------------------------------------------
// <auto-generated>
//     File: {fileName}
//     Author: {author}
//     Created: {DateTime.Now:yyyy-MM-dd}
// </auto-generated>
// ------------------------------------------------------------------------------

";
await TypeAsync(header);
