// Macro: Insert file header
// Recorded: 2026-05-02T10:23:08Z
// Steps: 2
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

using static Macros.Engine.Scripting.Helpers;
using static Community.VisualStudio.Toolkit.VS;

// step 1: collect a few values for the header
string author = await PromptAsync("Author:", Environment.UserName);
string fileName = Context.CurrentDocument?.Name ?? "NewFile.cs";

// step 2: insert a multi-line header at the current caret position
var header = $@"// ------------------------------------------------------------------------------
// <auto-generated>
//     File: {fileName}
//     Author: {author}
//     Created: {DateTime.Now:yyyy-MM-dd}
// </auto-generated>
// ------------------------------------------------------------------------------

";
await TypeAsync(header);
