// Macro: Log active document path to Output Window
// Recorded: 2026-05-02T10:23:08Z
// Steps: 0
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

var doc = DTE.ActiveDocument;
if (doc?.FullName != null)
{
    var outputWindow = DTE.ToolWindows.OutputWindow;
    var pane = outputWindow.OutputWindowPanes.Item("Debug");
    pane.Activate();
    pane.OutputString($"Active document: {doc.FullName}\n");
}
