// Macro: Show build error count in status bar
// Recorded: 2026-05-02T10:23:08Z
// Steps: 0
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// @trigger Build.SolutionBuildDone
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

int errors = (int?)Trigger?.Data?["ErrorCount"] ?? 0;
int warnings = (int?)Trigger?.Data?["WarningCount"] ?? 0;
await VS.StatusBar.ShowMessageAsync($"Build complete: {errors} error(s), {warnings} warning(s)");
