// Macro: Sort selected lines alphabetically
// Recorded: 2026-05-02T10:23:08Z
// Steps: 0
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

var sel = DTE.ActiveDocument?.Selection as EnvDTE.TextSelection;
if (sel?.IsEmpty == true)
{
    await VS.MessageBox.ShowWarningAsync("Macros", "No text selected");
    return;
}

var lines = sel.Text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
Array.Sort(lines);
sel.Insert(string.Join("\n", lines), (int)EnvDTE.vsInsertFlags.vsInsertFlagsInsertAtStart);
