// Macro: Toggle between // and /* */ comment styles
// Recorded: 2026-05-02T10:23:08Z
// Steps: 0
// Generated by Macros — edit freely.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// See Tools → Options → Macros → Available Triggers for the full list.

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"

var sel = DTE.ActiveDocument?.Selection as EnvDTE.TextSelection;
if (sel?.IsEmpty == true)
{
    await VS.StatusBar.ShowMessageAsync("Macros: No text selected");
    return;
}

var text = sel.Text;
if (text.StartsWith("//"))
{
    var commented = text.Substring(2).Trim();
    sel.Insert($"/* {commented} */", (int)EnvDTE.vsInsertFlags.vsInsertFlagsInsertAtStart);
}
else if (text.StartsWith("/*") && text.EndsWith("*/"))
{
    var uncommented = text.Substring(2, text.Length - 4).Trim();
    sel.Insert($"// {uncommented}", (int)EnvDTE.vsInsertFlags.vsInsertFlagsInsertAtStart);
}
