using System;
using System.Collections.Generic;
using System.Linq;
using Macros.Engine.Scripting;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Macros.Tests.Scripting;

/// <summary>
/// Tests for <see cref="IntelliSenseShim"/>. The generator is pure (no I/O), so every test
/// is fully deterministic and requires no temp-folder setup.
/// </summary>
public sealed class IntelliSenseShimTests
{
    private static readonly IReadOnlyList<string> SamplePaths = new[]
    {
        @"C:\path\to\EnvDTE.dll",
        @"C:\path\to\EnvDTE80.dll",
        @"C:\path\to\Macros.Engine.dll",
    };

    // ── Header ───────────────────────────────────────────────────────────────────────

    [Fact]
    public void Generate_StartsWithExactFirstHeaderLine()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);
        Assert.StartsWith("// Macros — IntelliSense Shim\n", shim);
    }

    [Fact]
    public void Generate_ContainsAllFixedHeaderLines()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);

        Assert.Contains("// Macros — IntelliSense Shim\n", shim);
        Assert.Contains("// Auto-generated. Do not edit. Regenerated by the Macros VSIX on package load.\n", shim);
        Assert.Contains("// This file makes #r and using directives resolve in the C# editor when a\n", shim);
        Assert.Contains("// .csx macro is opened in Visual Studio. The Macros runtime player ignores\n", shim);
        Assert.Contains("// it via a custom SourceReferenceResolver — globals come from MacroGlobals.\n", shim);
    }

    // ── #r directives ────────────────────────────────────────────────────────────────

    [Fact]
    public void Generate_ContainsVerbatimReferenceDirectiveForEachPath()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);

        foreach (string path in SamplePaths)
        {
            string expected = $"#r \"{path}\"";
            Assert.Contains(expected, shim, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void Generate_ReferenceDirectivesAreInSuppliedOrder()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);

        int prev = -1;
        foreach (string path in SamplePaths)
        {
            int idx = shim.IndexOf($"#r \"{path}\"", StringComparison.Ordinal);
            Assert.True(idx >= 0, $"#r directive for '{path}' not found.");
            Assert.True(idx > prev, $"#r directive for '{path}' is out of expected order.");
            prev = idx;
        }
    }

    [Fact]
    public void Generate_ReferenceDirective_BackslashPathsAreEmittedLiterally()
    {
        // Roslyn's #r parser does not process escape sequences — backslashes in paths
        // are raw characters, not escape prefixes. The generator must emit them as-is.
        var paths = new[] { @"C:\some\path\Assembly.dll" };
        string shim = IntelliSenseShim.Generate(paths);

        // The path must appear verbatim inside #r "…" (single backslashes, not doubled).
        Assert.Contains("#r \"C:\\some\\path\\Assembly.dll\"", shim, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_ReferenceDirective_PathWithDoubleQuote_IsStripped()
    {
        // A double-quote inside a path would terminate the #r string and corrupt the
        // directive. The generator defensively strips it (paths virtually never have one).
        var paths = new[] { "C:\\weird\"path\\Assembly.dll" };
        string shim = IntelliSenseShim.Generate(paths);

        // The `"` in the middle of the path should be removed.
        Assert.Contains("#r \"C:\\weirdpath\\Assembly.dll\"", shim, StringComparison.Ordinal);
    }

    // ── using directives ─────────────────────────────────────────────────────────────

    [Fact]
    public void Generate_ContainsAllUsingDirectivesInOrder()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);

        string[] expectedUsings =
        {
            "using System;",
            "using System.Diagnostics;",
            "using System.Threading.Tasks;",
            "using EnvDTE;",
            "using EnvDTE80;",
            "using Community.VisualStudio.Toolkit;",
            "using Macros.Engine.Scripting;",
            "using Macros.Engine.Triggers;",
            "using static Macros.Engine.Scripting.Helpers;",
            "using static Community.VisualStudio.Toolkit.VS;",
        };

        int prev = -1;
        foreach (string u in expectedUsings)
        {
            int idx = shim.IndexOf(u, StringComparison.Ordinal);
            Assert.True(idx >= 0, $"Expected '{u}' not found in shim.");
            Assert.True(idx > prev, $"'{u}' appears out of expected order.");
            prev = idx;
        }
    }

    // ── global stubs ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Generate_ContainsDTEStub()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);
        Assert.Contains("DTE2 DTE = null;", shim, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_ContainsContextStub()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);
        Assert.Contains("IMacroContext Context = null;", shim, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_ContainsTriggerStub()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);
        Assert.Contains("IMacroTrigger Trigger = null;", shim, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_StubsUseShortTypeNames()
    {
        // Short type names are used because usings above resolve them; avoids editor quirks.
        string shim = IntelliSenseShim.Generate(SamplePaths);
        Assert.Contains("DTE2 DTE = null;", shim, StringComparison.Ordinal);
        Assert.Contains("IMacroContext Context = null;", shim, StringComparison.Ordinal);
        Assert.Contains("IMacroTrigger Trigger = null;", shim, StringComparison.Ordinal);
    }

    // ── determinism + output contract ────────────────────────────────────────────────

    [Fact]
    public void Generate_IsDeterministic()
    {
        string first = IntelliSenseShim.Generate(SamplePaths);
        string second = IntelliSenseShim.Generate(SamplePaths);
        Assert.Equal(first, second);
    }

    [Fact]
    public void Generate_EndsWithNewline()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);
        Assert.EndsWith("\n", shim, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_EmptyPathList_ProducesValidShimWithNoRDirectives()
    {
        var shim = IntelliSenseShim.Generate(Array.Empty<string>());

        // Header must still be present.
        Assert.Contains("// Macros — IntelliSense Shim\n", shim, StringComparison.Ordinal);
        // No actual #r directives should appear (only the header comment mentions "#r" as prose).
        Assert.DoesNotContain("\n#r \"", shim, StringComparison.Ordinal);
        // Usings and stubs must still be emitted.
        Assert.Contains("using System;", shim, StringComparison.Ordinal);
        Assert.Contains("DTE2 DTE = null;", shim, StringComparison.Ordinal);
    }

    // ── argument validation ───────────────────────────────────────────────────────────

    [Fact]
    public void Generate_NullList_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => IntelliSenseShim.Generate(null!));
    }

    [Fact]
    public void Generate_NullEntry_ThrowsArgumentException()
    {
        var paths = new List<string> { @"C:\valid.dll", null! };
        var ex = Assert.Throws<ArgumentException>(() => IntelliSenseShim.Generate(paths));
        Assert.Equal("assemblyPaths", ex.ParamName);
    }

    [Fact]
    public void Generate_EmptyStringEntry_ThrowsArgumentException()
    {
        var paths = new List<string> { @"C:\valid.dll", "" };
        var ex = Assert.Throws<ArgumentException>(() => IntelliSenseShim.Generate(paths));
        Assert.Equal("assemblyPaths", ex.ParamName);
    }

    // ── parse sanity ─────────────────────────────────────────────────────────────────

    /// <summary>
    /// Confirms the generated shim is syntactically valid C# script text.
    /// Uses <see cref="CSharpSyntaxTree.ParseText"/> with <see cref="SourceCodeKind.Script"/>
    /// and checks that Roslyn reports no parse-level errors. The <c>#r</c> paths are fake
    /// (metadata resolution is never attempted during a parse-only pass).
    /// </summary>
    [Fact]
    public void Generate_ParseSanityCheck_NoSyntaxErrors()
    {
        string shim = IntelliSenseShim.Generate(SamplePaths);

        var tree = CSharpSyntaxTree.ParseText(
            shim,
            new CSharpParseOptions(
                languageVersion: LanguageVersion.Latest,
                kind: SourceCodeKind.Script));

        var errors = tree.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        Assert.Empty(errors);
    }
}
