// Macro: SampleMacro
// Recorded: 2025-04-30T21:48:37Z
// Steps: 5
// Generated by Macros — edit freely.
// Source format: C# Script (.csx) — executed by Macros.Engine.Player.MacroPlayer.
//
// To make this macro run automatically, add ONE OR MORE of these lines
// to the comment block above (remove the leading "// EXAMPLE: " prefix):
// EXAMPLE: // @trigger Build.SolutionBuildDone
// EXAMPLE: // @trigger Document.Saved when filename=*.cs
// EXAMPLE: // @trigger BeforeCommand File.Save
// EXAMPLE: // @trigger AfterCommand Build.BuildSolution
// See Tools → Options → Macros → Available Triggers for the full list.
//

// #load below pulls in the IntelliSense shim (auto-generated by the Macros VSIX)
// so the C# editor can resolve EnvDTE/EnvDTE80, the Toolkit's VS facade,
// the Macros Helpers, and script globals (DTE, Context, Trigger). The runtime
// player ignores this #load via a custom SourceReferenceResolver.
#load ".intellisense/Macros.Intellisense.csx"

// #r directives below are kept for external dotnet-script consumers; MacroPlayer
// supplies the same references via ScriptOptions at compile time.
#r "EnvDTE"
#r "EnvDTE80"

using System;
using System.Threading.Tasks;
using EnvDTE;
using EnvDTE80;
using Community.VisualStudio.Toolkit;
using Macros.Engine.Scripting;
using static Macros.Engine.Scripting.Helpers;
using static Community.VisualStudio.Toolkit.VS;

// step 1: insert 5 char(s) @ pos 0
await TypeAsync("Hello");
// step 2: command Edit.Copy
await ExecuteCommandAsync("Edit.Copy");
// step 3: insert 20 char(s) @ pos 10
await TypeAsync(@"Line1
Line2 ""quoted""");
// step 4: command 11111111-2222-3333-4444-555555555555/42
await RunCommandAsync(new System.Guid("11111111-2222-3333-4444-555555555555"), 42u);
// step 5: delete 3 char(s) @ pos 20
// TODO(m4-deletion-replay): deletion replay not yet supported; replaying via raw Edit.Delete which deletes the current selection, not the recorded range.
await ExecuteCommandAsync("Edit.Delete");
