// Macro: SampleMacro
// Recorded: 2025-04-30T21:48:37Z
// Generated by Macros — edit freely.
// Documentation: https://github.com/madskristensen/Macros/tree/master/docs

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"
using Community.VisualStudio.Toolkit;
using static Macros.Engine.Scripting.Helpers;

await TypeAsync("Hello");
await ExecuteCommandAsync("Edit.Copy");
await TypeAsync(@"Line1
Line2 ""quoted""");
// TODO(m4-deletion-replay): deletion replay not yet supported; replaying via raw Edit.Delete which deletes the current selection, not the recorded range.
await ExecuteCommandAsync("Edit.Delete");
