// Macro: SampleMacro
// Recorded: 2025-04-30T21:48:37Z
// Generated by Macros — edit freely.
// Documentation: https://github.com/madskristensen/Macros/tree/master/docs

// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).
#load ".intellisense/Macros.Intellisense.csx"
using Community.VisualStudio.Toolkit;
using static Macros.Engine.Scripting.Helpers;

// step 1: insert 5 char(s) @ pos 0
await TypeAsync("Hello");
// step 2: command Edit.Copy
await ExecuteCommandAsync("Edit.Copy");
// step 3: insert 20 char(s) @ pos 10
await TypeAsync(@"Line1
Line2 ""quoted""");
// step 4: delete 3 char(s) @ pos 20
// TODO(m4-deletion-replay): deletion replay not yet supported; replaying via raw Edit.Delete which deletes the current selection, not the recorded range.
await ExecuteCommandAsync("Edit.Delete");
