using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Macros.Engine.Codegen;
using Macros.Engine.Recording;
using Macros.Engine.Storage;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace Macros.Tests.Storage;

/// <summary>
/// Behavioural tests for <see cref="MacroFileLoadDirectiveMigrator"/>. Each test owns a
/// unique temp folder under the system temp root so xUnit's parallel runner can drive them
/// concurrently without cross-contamination.
/// </summary>
public sealed class MacroFileLoadDirectiveMigratorTests : IDisposable
{
    private readonly string _root;

    public MacroFileLoadDirectiveMigratorTests()
    {
        _root = Path.Combine(
            Path.GetTempPath(),
            "Macros.Tests.Migrator",
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_root))
            {
                Directory.Delete(_root, recursive: true);
            }
        }
        catch
        {
            // Best-effort cleanup.
        }
    }

    // ── helpers ───────────────────────────────────────────────────────────────────────

    private string Write(string name, string content)
    {
        string path = Path.Combine(_root, name);
        File.WriteAllText(path, content);
        return path;
    }

    private string Read(string name) => File.ReadAllText(Path.Combine(_root, name));

    /// <summary>
    /// Writes <paramref name="content"/> to <c><see cref="_root"/>\<paramref name="relativePath"/></c>,
    /// creating intermediate directories as needed.
    /// </summary>
    private string WriteAt(string relativePath, string content)
    {
        string path = Path.Combine(_root, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
        return path;
    }

    private string ReadAt(string relativePath) => File.ReadAllText(Path.Combine(_root, relativePath));

    /// <summary>
    /// Minimal pre-shim macro: header comments, #r directives, usings, body.
    /// Represents a file recorded before commit 12056f1.
    /// </summary>
    private static string PreShimMacro(string nl = "\n") =>
        string.Join(nl, new[]
        {
            "// Macro: OldMacro",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Steps: 1",
            "// Generated by Macros \u2014 edit freely.",
            "// Source format: C# Script (.csx) \u2014 executed by Macros.Engine.Player.MacroPlayer.",
            "//",
            "// Trigger guidance here.",
            "//",
            "",
            "// #r directives below are kept for external dotnet-script consumers; MacroPlayer",
            "// supplies the same references via ScriptOptions at compile time.",
            "#r \"EnvDTE\"",
            "#r \"EnvDTE80\"",
            "",
            "using System;",
            "using EnvDTE;",
            "",
            "// step 1: insert 5 char(s) @ pos 0",
            "await TypeAsync(\"Hello\");",
            "",
        }) + nl;   // preserve final newline

    // ── 1. Argument validation ─────────────────────────────────────────────────────

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void Migrate_NullOrEmptyStoreRoot_Throws(string? storeRoot)
    {
        Assert.Throws<ArgumentException>(() => MacroFileLoadDirectiveMigrator.Migrate(storeRoot!));
    }

    // ── 2. Missing folder ─────────────────────────────────────────────────────────

    [Fact]
    public void Migrate_MissingFolder_ReturnsEmptyResult()
    {
        string nonExistent = Path.Combine(_root, "does-not-exist");

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(nonExistent);

        Assert.Equal(0, result.Scanned);
        Assert.Equal(0, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);
    }

    // ── 3. Empty folder ───────────────────────────────────────────────────────────

    [Fact]
    public void Migrate_EmptyFolder_ReturnsZero()
    {
        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(0, result.Scanned);
        Assert.Equal(0, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);
    }

    // ── 4. Injection at correct position ─────────────────────────────────────────

    [Fact]
    public void Migrate_FileWithoutLoadDirective_InjectsAtCorrectPosition()
    {
        Write("old.csx", PreShimMacro());

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        string content = Read("old.csx");

        // Shim load directive is present.
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", content);

        // Obsolete #r directives are stripped.
        Assert.DoesNotContain("#r \"EnvDTE\"", content);
        Assert.DoesNotContain("#r \"EnvDTE80\"", content);

        // Macro body is unchanged.
        Assert.Contains("await TypeAsync(\"Hello\");", content);
    }

    // ── 5. File that already has #load is left unchanged ─────────────────────────

    [Fact]
    public void Migrate_FileWithExistingLoadDirective_InjectsUsings()
    {
        string original = "#load \".intellisense/Macros.Intellisense.csx\"\n\nawait TypeAsync(\"x\");\n";
        Write("modern.csx", original);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);
        string migrated = Read("modern.csx");
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);
        Assert.Contains("using Community.VisualStudio.Toolkit;", migrated);
        Assert.Contains("using static Macros.Engine.Scripting.Helpers;", migrated);
    }

    // ── 6. File with different #load is NOT skipped (no shim reference) ──────────

    [Fact]
    public void Migrate_FileWithDifferentLoadDirective_StillInjectsShim()
    {
        // A macro that loads some OTHER helper file — does NOT reference Macros.Intellisense.csx.
        string content = "#load \"helpers.csx\"\n\nusing System;\nawait TypeAsync(\"x\");\n";
        Write("other.csx", content);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        // The shim reference is absent → the file must be updated, not skipped.
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", Read("other.csx"));
    }

    // ── 7. All-comment file: shim block goes at end ───────────────────────────────

    [Fact]
    public void Migrate_AllCommentFile_AppendsBlock()
    {
        string content = "// Line1\n// Line2\n// Line3\n";
        Write("comments.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string result = Read("comments.csx");
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", result);

        // Original comment lines still present.
        Assert.Contains("// Line1", result);
        Assert.Contains("// Line3", result);
    }

    // ── 8. CRLF files stay CRLF ──────────────────────────────────────────────────

    [Fact]
    public void Migrate_PreservesCRLFLineEndings()
    {
        string content = PreShimMacro("\r\n");
        Write("crlf.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string result = Read("crlf.csx");

        // File must contain at least one CRLF sequence (not just bare LF).
        Assert.Contains("\r\n", result);

        // Verify no bare LF (i.e., every \n is preceded by \r).
        for (int i = 0; i < result.Length; i++)
        {
            if (result[i] == '\n')
            {
                Assert.True(i > 0 && result[i - 1] == '\r',
                    "Found a bare LF in a file that started with CRLF line endings.");
            }
        }
    }

    // ── 9. LF files stay LF ──────────────────────────────────────────────────────

    [Fact]
    public void Migrate_PreservesLFLineEndings()
    {
        string content = PreShimMacro("\n");
        Write("lf.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string result = Read("lf.csx");

        // No CRLF sequences should appear.
        Assert.DoesNotContain("\r\n", result);

        // Still contains LF-terminated lines.
        Assert.Contains("\n", result);
    }

    // ── 10. No .tmp files left behind after success ───────────────────────────────

    [Fact]
    public void Migrate_AtomicWrite_NoTempLeftBehind()
    {
        Write("macro.csx", PreShimMacro());

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string[] tmpFiles = Directory.GetFiles(_root, "*.tmp");
        Assert.Empty(tmpFiles);
    }

    // ── 11. Shim file itself is skipped ──────────────────────────────────────────

    [Fact]
    public void Migrate_SkipsShimFileItself()
    {
        // A copy of the shim dropped directly in the store root (unusual but possible).
        string shimContent = "// shim file\n#r \"SomeAssembly.dll\"\n";
        Write("Macros.Intellisense.csx", shimContent);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(0, result.Updated);
        Assert.Equal(1, result.Skipped);
        Assert.Empty(result.Errors);
        // Content untouched.
        Assert.Equal(shimContent, Read("Macros.Intellisense.csx"));
    }

    // ── 12. Recurses into subfolders (global store named-macro layout) ───────────────

    [Fact]
    public void Migrate_RecursesIntoSubfolders_LikeGlobalNamedMacroLayout()
    {
        // Root-level macro (mirrors current.csx in the global store).
        Write("root.csx", PreShimMacro());

        // Subfolder macro (mirrors %APPDATA%\Macros\Macros\namedMacro.csx).
        WriteAt(Path.Combine("Macros", "namedMacro.csx"), PreShimMacro());

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(2, result.Scanned);
        Assert.Equal(2, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", Read("root.csx"));
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"",
            ReadAt(Path.Combine("Macros", "namedMacro.csx")));
    }

    // ── 12b. .intellisense\ subfolder is excluded (even for non-shim .csx) ──────────

    [Fact]
    public void Migrate_SkipsIntelliSenseSubfolder_EvenWhenItContainsCsx()
    {
        // A non-shim .csx dropped inside .intellisense\ must not be visited at all.
        WriteAt(Path.Combine(".intellisense", "extra.csx"), PreShimMacro());

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(0, result.Scanned);
        Assert.Equal(0, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        // The file itself must be untouched.
        Assert.Equal(PreShimMacro(), ReadAt(Path.Combine(".intellisense", "extra.csx")));
    }

    [Fact]
    public void Migrate_SkipsIntelliSenseSubfolderCaseInsensitively()
    {
        // Folder name in all-caps — must still be excluded.
        WriteAt(Path.Combine(".INTELLISENSE", "extra.csx"), PreShimMacro());

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(0, result.Scanned);
        Assert.Equal(0, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);
    }

    // ── 12c. Full global store layout end-to-end ─────────────────────────────────────

    [Fact]
    public void Migrate_HandlesGlobalLayoutCorrectly()
    {
        // Exact mirror of %APPDATA%\Macros\ as it exists on Mads's machine.
        Write("current.csx", PreShimMacro());
        WriteAt(Path.Combine(".intellisense", "Macros.Intellisense.csx"), "// shim\n");
        WriteAt(Path.Combine("Macros", "namedA.csx"), PreShimMacro());
        WriteAt(Path.Combine("Macros", "namedB.csx"), PreShimMacro());

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        // .intellisense\ is excluded → only current + namedA + namedB are counted.
        Assert.Equal(3, result.Scanned);
        Assert.Equal(3, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", Read("current.csx"));
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"",
            ReadAt(Path.Combine("Macros", "namedA.csx")));
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"",
            ReadAt(Path.Combine("Macros", "namedB.csx")));

        // Shim file itself is untouched.
        Assert.Equal("// shim\n", ReadAt(Path.Combine(".intellisense", "Macros.Intellisense.csx")));
    }

    // ── 12d. File whose name contains ".intellisense" is NOT skipped ─────────────────

    [Fact]
    public void Migrate_FilenameContainingDotIntellisense_IsNotSkipped()
    {
        // Segment equality, not substring — my.intellisense.csx is a valid macro file.
        WriteAt(Path.Combine("Macros", "my.intellisense.csx"), PreShimMacro());

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"",
            ReadAt(Path.Combine("Macros", "my.intellisense.csx")));
    }

    // ── 13. Per-file error captured; other files still processed ─────────────────

    [Fact]
    public void Migrate_PerFileErrorIsCaptured_OthersStillProcessed()
    {
        // Write two macro files; lock one to cause a read failure.
        string goodPath = Write("good.csx", PreShimMacro());
        string badPath  = Write("bad.csx",  PreShimMacro());

        MigrationResult result;

        // Hold bad.csx open with FileShare.None to prevent the migrator from reading it.
        using (var lockStream = new FileStream(badPath, FileMode.Open, FileAccess.ReadWrite, FileShare.None))
        {
            result = MacroFileLoadDirectiveMigrator.Migrate(_root);
        }

        Assert.Equal(2, result.Scanned);

        // Exactly one error for the locked file.
        string singleError = Assert.Single(result.Errors);
        Assert.Contains("bad.csx", singleError);

        // The good file was still updated.
        Assert.Equal(1, result.Updated);

        // Invariant: Scanned == Updated + Skipped + Errors.Count
        Assert.Equal(result.Scanned, result.Updated + result.Skipped + result.Errors.Count);
    }

    // ── 14. Idempotent: second call leaves everything Skipped ────────────────────

    [Fact]
    public void Migrate_IsIdempotent()
    {
        Write("macro.csx", PreShimMacro());

        MigrationResult first  = MacroFileLoadDirectiveMigrator.Migrate(_root);
        string afterFirst = Read("macro.csx");

        MigrationResult second = MacroFileLoadDirectiveMigrator.Migrate(_root);
        string afterSecond = Read("macro.csx");

        Assert.Equal(1, first.Updated);

        // Second run: Updated=0, file Skipped.
        Assert.Equal(0, second.Updated);
        Assert.Equal(1, second.Skipped);

        // File content is unchanged between first and second run.
        Assert.Equal(afterFirst, afterSecond);

        // Only one #load line in the file (not duplicated).
        int count = CountOccurrences(afterSecond, "#load \".intellisense/Macros.Intellisense.csx\"");
        Assert.Equal(1, count);
    }

    // ── 15. Round-trip is Roslyn-parseable ───────────────────────────────────────

    [Fact]
    public void Migrate_RoundTripIsRoslynParseable()
    {
        // Generate a fresh macro with the current codegen.
        var steps = new RecordedStep[]
        {
            new TextEditStep(0, 0, "", "hello"),
            new RecordedStep.CommandStep(Guid.NewGuid(), 1u, "Edit.Copy"),
        };
        DateTime utc = new DateTime(2026, 5, 1, 23, 30, 25, DateTimeKind.Utc);
        string freshSource = CSharpCodeGenerator.Generate(steps, "RoundTrip", utc);

        // Simulate a pre-shim file by removing the entire shim block emitted by
        // EmitReferenceDirectives (comment + #load + usings + blank line).
        const string shimCommentLine = "// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).\n";
        int blockBegin = freshSource.IndexOf(shimCommentLine, StringComparison.Ordinal);
        Assert.True(blockBegin >= 0, "Fresh codegen output should contain the shim comment line.");

        // Find the blank line that terminates the block (after the usings).
        // The block ends at the first blank line after blockBegin.
        int searchPos = blockBegin;
        int blockEnd = blockBegin;
        while (searchPos < freshSource.Length)
        {
            int nlPos = freshSource.IndexOf('\n', searchPos);
            if (nlPos < 0) { blockEnd = freshSource.Length; break; }
            string line = freshSource.Substring(searchPos, nlPos - searchPos);
            if (searchPos > blockBegin && line.Trim().Length == 0)
            {
                blockEnd = nlPos + 1; // include the blank line's newline
                break;
            }
            searchPos = nlPos + 1;
        }

        string preShimSource = freshSource.Remove(blockBegin, blockEnd - blockBegin);

        Write("roundtrip.csx", preShimSource);
        MacroFileLoadDirectiveMigrator.Migrate(_root);
        string migrated = Read("roundtrip.csx");

        // 1. The #load directive is present after migration.
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);

        // 2. Roslyn can parse the migrated content without syntax errors.
        AssertNoSyntaxErrors(migrated);

        // 3. The macro body is preserved.
        Assert.Contains("await TypeAsync(\"hello\");", migrated);
        Assert.Contains("await ExecuteCommandAsync(\"Edit.Copy\");", migrated);
    }

    // ── 16. @trigger comment in header: #load injected before first #r ───────────────

    [Fact]
    public void Migrate_HandlesTriggerDirectiveInComments_StillInjectsBeforeFirstRDirective()
    {
        // Exact shape from Mads's RecordedMacro.csx: the // @trigger line sits in the
        // header block (it's a comment), so FindBodyStart skips past it and injection
        // lands immediately above the first #r directive.
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: RecordedMacro",
            "// Recorded: 2026-05-01T19:35:25Z",
            "// Steps: 1",
            "// Generated by Macros \u2014 edit freely.",
            "// Source format: C# Script (.csx) \u2014 executed by Macros.Engine.Player.MacroPlayer.",
            "//",
            "// See Tools \u2192 Options \u2192 Macros \u2192 Available Triggers for the full list.",
            "//",
            "// #r directives below are for editor IntelliSense and external dotnet-script",
            "// runs; MacroPlayer supplies the same references via ScriptOptions at compile time.",
            "// @trigger AfterCommand File.SaveAll",
            "#r \"EnvDTE\"",
            "#r \"EnvDTE80\"",
            "",
            "using System;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("recorded.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string migrated = Read("recorded.csx");

        // The #load block must be present.
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);

        // The obsolete #r directives must be stripped.
        Assert.DoesNotContain("#r \"EnvDTE\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE80\"", migrated);

        // The // @trigger line is still present, and it precedes the injected #load block.
        int loadPos    = migrated.IndexOf("#load \".intellisense/Macros.Intellisense.csx\"", StringComparison.Ordinal);
        int triggerPos = migrated.IndexOf("// @trigger AfterCommand File.SaveAll", StringComparison.Ordinal);
        Assert.True(triggerPos >= 0, "// @trigger line must be preserved.");
        Assert.True(triggerPos < loadPos, "// @trigger header comment must remain before the injected #load block.");
    }

    // ── 17. Strip Pattern A obsolete #r block (post-12056f1 comment) ────────────────

    [Fact]
    public void Migrate_StripsObsoleteREnvDTEBlock_PatternA()
    {
        // A file that already has #load (was previously migrated) but was generated
        // by codegen between commit 12056f1 and the drop-#r change — it still carries
        // the Pattern A #r comment block.
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: AlreadyMigrated",
            "// Recorded: 2025-06-01T00:00:00Z",
            "// Steps: 1",
            "//",
            "",
            "// #load below pulls in the IntelliSense shim (auto-generated by the Macros VSIX)",
            "// so the C# editor can resolve EnvDTE/EnvDTE80, the Toolkit's VS facade,",
            "// the Macros Helpers, and script globals (DTE, Context, Trigger). The runtime",
            "// player ignores this #load via a custom SourceReferenceResolver.",
            "#load \".intellisense/Macros.Intellisense.csx\"",
            "",
            "// #r directives below are kept for external dotnet-script consumers; MacroPlayer",
            "// supplies the same references via ScriptOptions at compile time.",
            "#r \"EnvDTE\"",
            "#r \"EnvDTE80\"",
            "",
            "using System;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("pattern-a.csx", content);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        string migrated = Read("pattern-a.csx");
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE80\"", migrated);
        Assert.Contains("await TypeAsync(\"hello\");", migrated);
    }

    // ── 18. Strip Pattern B obsolete #r block (pre-12056f1 comment) ─────────────────

    [Fact]
    public void Migrate_StripsObsoleteREnvDTEBlock_PatternB()
    {
        // A file from before commit 12056f1 — no #load, and has the older Pattern B
        // comment that referenced both editor IntelliSense and external dotnet-script.
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: OldStyle",
            "// Recorded: 2024-12-01T00:00:00Z",
            "// Steps: 1",
            "//",
            "",
            "// #r directives below are for editor IntelliSense and external dotnet-script",
            "// runs; MacroPlayer supplies the same references via ScriptOptions at compile time.",
            "#r \"EnvDTE\"",
            "#r \"EnvDTE80\"",
            "",
            "using System;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("pattern-b.csx", content);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);
        Assert.Empty(result.Errors);

        string migrated = Read("pattern-b.csx");
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE80\"", migrated);
        Assert.Contains("await TypeAsync(\"hello\");", migrated);
    }

    // ── 19. Trigger line intervenes between comment and #r directives ────────────────

    [Fact]
    public void Migrate_StripsObsoleteRBlock_EvenWhenTriggerLineIntervenes()
    {
        // Exact shape from Mads's RecordedMacro.csx: the // @trigger comment sits between
        // the #r-comment block and the #r lines.  After migration the trigger line must
        // survive; the #r lines must be gone; #load must be injected.
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: RecordedMacro2",
            "// Recorded: 2026-05-01T19:35:25Z",
            "// Steps: 1",
            "// Generated by Macros \u2014 edit freely.",
            "// Source format: C# Script (.csx) \u2014 executed by Macros.Engine.Player.MacroPlayer.",
            "//",
            "// See Tools \u2192 Options \u2192 Macros \u2192 Available Triggers for the full list.",
            "//",
            "// #r directives below are for editor IntelliSense and external dotnet-script",
            "// runs; MacroPlayer supplies the same references via ScriptOptions at compile time.",
            "// @trigger AfterCommand File.SaveAll",
            "#r \"EnvDTE\"",
            "#r \"EnvDTE80\"",
            "",
            "using System;",
            "",
            "await TypeAsync(\"hello2\");",
            "",
        }) + nl;

        Write("trigger-intervenes.csx", content);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Scanned);
        Assert.Equal(1, result.Updated);
        Assert.Equal(0, result.Skipped);

        string migrated = Read("trigger-intervenes.csx");

        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE80\"", migrated);
        Assert.Contains("// @trigger AfterCommand File.SaveAll", migrated);

        // Trigger line stays in the header comment block, before the injected #load.
        int triggerPos = migrated.IndexOf("// @trigger AfterCommand File.SaveAll", StringComparison.Ordinal);
        int loadPos    = migrated.IndexOf("#load \".intellisense/Macros.Intellisense.csx\"", StringComparison.Ordinal);
        Assert.True(triggerPos < loadPos,
            $"// @trigger (pos {triggerPos}) should precede #load (pos {loadPos}).");
    }

    // ── 20. User-added #r directives for other assemblies are preserved ───────────────

    [Fact]
    public void Migrate_DoesNotStripUserAddedRDirectives()
    {
        // Only the exact #r "EnvDTE" and #r "EnvDTE80" lines are removed.
        // A user-written #r for another library must survive untouched.
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: Custom",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Steps: 1",
            "//",
            "",
            "// #r directives below are kept for external dotnet-script consumers; MacroPlayer",
            "// supplies the same references via ScriptOptions at compile time.",
            "#r \"EnvDTE\"",
            "#r \"EnvDTE80\"",
            "#r \"MyCustomLib\"",
            "",
            "using System;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("custom-r.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string migrated = Read("custom-r.csx");

        // Obsolete built-in #r lines are gone.
        Assert.DoesNotContain("#r \"EnvDTE\"", migrated);
        Assert.DoesNotContain("#r \"EnvDTE80\"", migrated);

        // User's custom reference survives.
        Assert.Contains("#r \"MyCustomLib\"", migrated);

        // Shim is present.
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);
    }

    // ── 21. Stripping the #r block is idempotent ─────────────────────────────────────

    [Fact]
    public void Migrate_StripsObsoleteRBlock_IsIdempotent()
    {
        Write("idempotent-r.csx", PreShimMacro());

        MigrationResult first  = MacroFileLoadDirectiveMigrator.Migrate(_root);
        string afterFirst = Read("idempotent-r.csx");

        MigrationResult second = MacroFileLoadDirectiveMigrator.Migrate(_root);
        string afterSecond = Read("idempotent-r.csx");

        // First run: shim injected + #r stripped.
        Assert.Equal(1, first.Updated);
        Assert.Equal(0, first.Skipped);

        // Second run: nothing to do.
        Assert.Equal(0, second.Updated);
        Assert.Equal(1, second.Skipped);

        // Content unchanged between first and second run.
        Assert.Equal(afterFirst, afterSecond);

        // No obsolete #r in final output.
        Assert.DoesNotContain("#r \"EnvDTE\"", afterSecond);
        Assert.DoesNotContain("#r \"EnvDTE80\"", afterSecond);

        // Exactly one #load line (not duplicated).
        int count = CountOccurrences(afterSecond, "#load \".intellisense/Macros.Intellisense.csx\"");
        Assert.Equal(1, count);
    }

    // ── 22. Only exact EnvDTE references are stripped; near-matches are left alone ───

    [Fact]
    public void Migrate_OnlyStripsExactEnvDTEReferences()
    {
        // #r "EnvDTEFake" and #r "EnvDTE.Custom" are NOT the exact obsolete lines;
        // they must survive migration untouched.
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: FakeEnvDTE",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Steps: 1",
            "//",
            "",
            "#r \"EnvDTEFake\"",
            "#r \"EnvDTE.Custom\"",
            "",
            "using System;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("fake-envdte.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string migrated = Read("fake-envdte.csx");

        // Near-match references stay.
        Assert.Contains("#r \"EnvDTEFake\"", migrated);
        Assert.Contains("#r \"EnvDTE.Custom\"", migrated);

        // Shim is still injected.
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", migrated);
    }

    // ── 23. Strip obsolete using block ───────────────────────────────────────────────

    [Fact]
    public void Migrate_InjectsMissingUsingsIntoExistingFile()
    {
        const string nl = "\n";
        // File has #load and some usings but is MISSING "using static Macros.Engine.Scripting.Helpers;"
        string content = string.Join(nl, new[]
        {
            "// Macro: WithUsings",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Steps: 1",
            "//",
            "",
            "#load \".intellisense/Macros.Intellisense.csx\"",
            "",
            "using System;",
            "using Community.VisualStudio.Toolkit;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("with-usings.csx", content);

        MigrationResult first = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, first.Scanned);
        Assert.Equal(1, first.Updated);
        Assert.Equal(0, first.Skipped);
        Assert.Empty(first.Errors);

        string afterFirst = Read("with-usings.csx");

        // Missing "using static Macros.Engine.Scripting.Helpers;" was injected.
        Assert.Contains("using static Macros.Engine.Scripting.Helpers;", afterFirst);
        // Existing usings and body preserved.
        Assert.Contains("using Community.VisualStudio.Toolkit;", afterFirst);
        Assert.Contains("await TypeAsync(\"hello\");", afterFirst);
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", afterFirst);

        // Idempotency: second call is a no-op.
        MigrationResult second = MacroFileLoadDirectiveMigrator.Migrate(_root);
        Assert.Equal(0, second.Updated);
        Assert.Equal(1, second.Skipped);
        Assert.Equal(afterFirst, Read("with-usings.csx"));
    }

    // ── 24. User-added usings survive; only standard ones are stripped ────────────────

    [Fact]
    public void Migrate_PreservesUserAddedUsings()
    {
        const string nl = "\n";
        // File has #load but is MISSING "using static Macros.Engine.Scripting.Helpers;"
        string content = string.Join(nl, new[]
        {
            "// Macro: Mixed",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Steps: 1",
            "//",
            "",
            "#load \".intellisense/Macros.Intellisense.csx\"",
            "",
            "using System;",
            "using System.IO;",
            "using Community.VisualStudio.Toolkit;",
            "using MyCompany.Custom;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("mixed-usings.csx", content);

        MacroFileLoadDirectiveMigrator.Migrate(_root);

        string result = Read("mixed-usings.csx");

        // Missing "using static Macros.Engine.Scripting.Helpers;" was injected.
        Assert.Contains("using static Macros.Engine.Scripting.Helpers;", result);
        // Existing usings survive.
        Assert.Contains("using Community.VisualStudio.Toolkit;", result);

        // User-added usings survive.
        Assert.Contains("using System.IO;", result);
        Assert.Contains("using MyCompany.Custom;", result);
    }

    // ── 25. 4-line verbose shim comment replaced with 1-line comment ─────────────────

    [Fact]
    public void Migrate_ReplacesFourLineShimCommentWithOneLine()
    {
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: VerboseShim",
            "// Recorded: 2025-01-01T00:00:00Z",
            "//",
            "",
            "// #load below pulls in the IntelliSense shim (auto-generated by the Macros VSIX)",
            "// so the C# editor can resolve EnvDTE/EnvDTE80, the Toolkit's VS facade,",
            "// the Macros Helpers, and script globals (DTE, Context, Trigger). The runtime",
            "// player ignores this #load via a custom SourceReferenceResolver.",
            "#load \".intellisense/Macros.Intellisense.csx\"",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("verbose-shim.csx", content);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Updated);

        string after = Read("verbose-shim.csx");

        // New single-line comment is present.
        Assert.Contains(
            "// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).",
            after);

        // Old verbose lines are gone.
        Assert.DoesNotContain("// #load below pulls in the IntelliSense shim", after);
        Assert.DoesNotContain("// so the C# editor can resolve", after);
        Assert.DoesNotContain("// the Macros Helpers", after);
        Assert.DoesNotContain("// player ignores this #load", after);

        // #load line is preserved.
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", after);
    }

    // ── 26. Source-format line is stripped ───────────────────────────────────────────

    [Fact]
    public void Migrate_StripsSourceFormatLine()
    {
        const string nl = "\n";
        string content = string.Join(nl, new[]
        {
            "// Macro: OldFormat",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Generated by Macros \u2014 edit freely.",
            "// Source format: C# Script (.csx) \u2014 executed by Macros.Engine.Player.MacroPlayer.",
            "//",
            "",
            "#load \".intellisense/Macros.Intellisense.csx\"",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("source-format.csx", content);

        MigrationResult result = MacroFileLoadDirectiveMigrator.Migrate(_root);

        Assert.Equal(1, result.Updated);

        string after = Read("source-format.csx");
        Assert.DoesNotContain("// Source format:", after);
        Assert.Contains("#load \".intellisense/Macros.Intellisense.csx\"", after);
        Assert.Contains("await TypeAsync(\"hello\");", after);
    }

    // ── 27. All slim changes are idempotent ──────────────────────────────────────────

    [Fact]
    public void Migrate_AllSlimChangesIdempotent()
    {
        // A file that has the shim and all required usings is left unchanged.
        const string nl = "\n";
        string fullyMigrated = string.Join(nl, new[]
        {
            "// Macro: Slimmed",
            "// Recorded: 2025-01-01T00:00:00Z",
            "// Generated by Macros \u2014 edit freely.",
            "//",
            "",
            "// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).",
            "#load \".intellisense/Macros.Intellisense.csx\"",
            "using EnvDTE;",
            "using EnvDTE80;",
            "using Community.VisualStudio.Toolkit;",
            "using Macros.Engine.Scripting;",
            "using Macros.Engine.Triggers;",
            "using static Macros.Engine.Scripting.Helpers;",
            "using static Community.VisualStudio.Toolkit.VS;",
            "",
            "await TypeAsync(\"hello\");",
            "",
        }) + nl;

        Write("fully-slimmed.csx", fullyMigrated);

        MigrationResult first  = MacroFileLoadDirectiveMigrator.Migrate(_root);
        string afterFirst  = Read("fully-slimmed.csx");

        MigrationResult second = MacroFileLoadDirectiveMigrator.Migrate(_root);
        string afterSecond = Read("fully-slimmed.csx");

        Assert.Equal(0, first.Updated);
        Assert.Equal(1, first.Skipped);
        Assert.Equal(0, second.Updated);
        Assert.Equal(1, second.Skipped);
        Assert.Equal(fullyMigrated, afterFirst);
        Assert.Equal(afterFirst, afterSecond);
    }

    // ── private helpers ───────────────────────────────────────────────────────────

    private static int CountOccurrences(string haystack, string needle)
    {
        int count = 0;
        int pos = 0;
        while ((pos = haystack.IndexOf(needle, pos, StringComparison.Ordinal)) >= 0)
        {
            count++;
            pos += needle.Length;
        }

        return count;
    }

    private static void AssertNoSyntaxErrors(string source)
    {
        var tree = CSharpSyntaxTree.ParseText(
            SourceText.From(source),
            new CSharpParseOptions(kind: SourceCodeKind.Script, languageVersion: LanguageVersion.Latest));

        var errors = tree.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToArray();

        Assert.True(
            errors.Length == 0,
            "Migrated source has syntax errors:\n" +
            string.Join("\n", errors.Select(e => e.ToString())) +
            "\n\nSource:\n" + source);
    }
}
