// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Macros
{
    internal sealed partial class Vsix
    {
        public const string Id = "Macros.MadsKristensen.d13e532a-bd43-40df-ae9f-8d05e54138c7";
        public const string Name = "Macros";
        public const string Description = @"Record text edits and IDE actions. Replay instantly with hotkeys or trigger on events. Every macro is editable C# script. Modern, powerful, open-source macros";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "macros, automation, recording, replay";
        public const bool IsPreview = false;
    }
}
