// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Macros
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMacrosPackageString = "d13e532a-bd43-40df-ae9f-8d05e54138c7";
        public static Guid guidMacrosPackage = new Guid(guidMacrosPackageString);

        public const string guidMacrosPackageCmdSetString = "1f6e8c4b-2d54-4a76-9c2c-9d8b5a7e1d31";
        public static Guid guidMacrosPackageCmdSet = new Guid(guidMacrosPackageCmdSetString);

        public const string guidMacrosRecordingContextString = "f0a5d2c7-7e7c-4a47-bc6f-2c0a5b6f2c80";
        public static Guid guidMacrosRecordingContext = new Guid(guidMacrosRecordingContextString);

        public const string guidMacrosNotRecordingContextString = "c8e5a3b1-9f4d-4d87-b5a2-7e1f3a8c2d40";
        public static Guid guidMacrosNotRecordingContext = new Guid(guidMacrosNotRecordingContextString);

        public const string guidMacrosToolWindowString = "a4c1b2d8-3e5f-4a6b-9c7d-8e0f1a2b3c4d";
        public static Guid guidMacrosToolWindow = new Guid(guidMacrosToolWindowString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MacrosToolbar = 0x1000;
        public const int MacrosToolbarGroup = 0x1010;
        public const int MacrosToolWindowToolbar = 0x1020;
        public const int MacrosToolWindowToolbarGroup = 0x1030;
        public const int MacrosContextMenu = 0x1040;
        public const int MacrosContextMenuGroup = 0x1050;
        public const int cmdidMacrosRecord = 0x0100;
        public const int cmdidMacrosStop = 0x0101;
        public const int cmdidMacrosPlayLast = 0x0102;
        public const int cmdidMacrosPlayNamed = 0x0103;
        public const int cmdidMacrosSaveAs = 0x0104;
        public const int cmdidMacrosShowWindow = 0x0105;
        public const int cmdidMacrosDelete = 0x0106;
        public const int cmdidMacrosRename = 0x0107;
        public const int cmdidMacrosEdit = 0x0108;
        public const int cmdidMacrosManageTriggers = 0x0109;
        public const int cmdidMacrosNewMacro = 0x010A;
        public const int cmdidMacrosRefresh = 0x010B;
        public const int cmdidMacrosMoveToRepo = 0x010C;
        public const int cmdidMacrosMoveToGlobal = 0x010D;
        public const int cmdidMacrosToggleTriggers = 0x0014;
        public const int MacrosToolWindowContextMenu = 0x2000;
        public const int MacrosContextMenuGroup1 = 0x2100;
        public const int MacrosContextMenuGroup2 = 0x2200;
        public const int MacrosContextMenuGroup3 = 0x2300;
        public const int cmdidMacrosCtxPlay = 0x2110;
        public const int cmdidMacrosCtxEdit = 0x2111;
        public const int cmdidMacrosCtxRename = 0x2112;
        public const int cmdidMacrosCtxDelete = 0x2113;
        public const int cmdidMacrosCtxMoveToRepo = 0x2114;
        public const int cmdidMacrosCtxMoveToGlobal = 0x2115;
        public const int cmdidMacrosCtxManageTriggers = 0x2116;
        public const int cmdidMacrosCtxCopyToRepo = 0x2117;
        public const int cmdidMacrosCtxCopyToGlobal = 0x2118;
        public const int cmdidMacrosCtxOpenFolder = 0x2210;
        public const int MacrosToolWindowGroupContextMenu = 0x2400;
        public const int MacrosGroupContextMenuGroup1 = 0x2410;
    }
}
