using System;
using System.Collections.Generic;
using System.Text;

namespace Macros.Engine.Scripting;

/// <summary>
/// Pure, deterministic generator that produces the IntelliSense shim source
/// (<c>Macros.Intellisense.csx</c>) from a caller-supplied list of assembly paths.
/// </summary>
/// <remarks>
/// <para>
/// <b>Pure.</b> No I/O, no statics, no clock. The caller (see
/// <see cref="IntelliSenseShimWriter"/>) decides which assemblies to include; this class
/// just emits the source text.
/// </para>
/// <para>
/// <b>Output contract.</b> The emitted script:
/// (1) opens with fixed header comments that describe the file's purpose;
/// (2) emits one <c>#r @"…"</c> verbatim directive per assembly path, in the order
///     the caller supplied;
/// (3) emits the standard <c>using</c> and <c>using static</c> directives that cover the
///     full IntelliSense surface (DTE, Community Toolkit, Macros.Engine helper vocab);
/// (4) declares editor-only stubs for the script globals (<c>DTE</c>, <c>Context</c>,
///     <c>Trigger</c>) matching the shape of <see cref="MacroGlobals"/>. These let the
///     C# language service resolve the names when it opens the <c>.csx</c> file; the
///     macro player never sees them (its <c>SourceReferenceResolver</c> returns an empty
///     stream for this file).
/// </para>
/// <para>
/// <b>Line endings.</b> All emitted line breaks are bare <c>\n</c>, consistent with
/// <see cref="Codegen.CSharpCodeGenerator"/>.
/// </para>
/// </remarks>
public static class IntelliSenseShim
{
    /// <summary>Generates the complete shim source string from the supplied assembly paths.</summary>
    /// <param name="assemblyPaths">
    /// Absolute paths to the DLLs that require <c>#r</c> references. Emitted in the order
    /// supplied — no sorting is applied. Must not be <see langword="null"/>, and no entry
    /// may be <see langword="null"/> or empty.
    /// </param>
    /// <returns>A <c>.csx</c>-compatible shim source string ending with a newline.</returns>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="assemblyPaths"/> is <see langword="null"/>.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// Any entry in <paramref name="assemblyPaths"/> is <see langword="null"/> or empty.
    /// </exception>
    public static string Generate(IReadOnlyList<string> assemblyPaths)
    {
        if (assemblyPaths is null) throw new ArgumentNullException(nameof(assemblyPaths));

        for (int i = 0; i < assemblyPaths.Count; i++)
        {
            if (string.IsNullOrEmpty(assemblyPaths[i]))
            {
                throw new ArgumentException(
                    $"Assembly path at index {i} is null or empty.",
                    nameof(assemblyPaths));
            }
        }

        var sb = new StringBuilder(capacity: 512 + (assemblyPaths.Count * 80));
        EmitHeader(sb);
        EmitReferenceDirectives(sb, assemblyPaths);
        EmitUsings(sb);
        EmitGlobalStubs(sb);
        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb)
    {
        sb.Append("// Macros — IntelliSense Shim\n");
        sb.Append("// Auto-generated. Do not edit. Regenerated by the Macros VSIX on package load.\n");
        sb.Append("// This file makes #r and using directives resolve in the C# editor when a\n");
        sb.Append("// .csx macro is opened in Visual Studio. The Macros runtime player ignores\n");
        sb.Append("// it via a custom SourceReferenceResolver — globals come from MacroGlobals.\n");
        sb.Append('\n');
    }

    private static void EmitReferenceDirectives(StringBuilder sb, IReadOnlyList<string> assemblyPaths)
    {
        foreach (string path in assemblyPaths)
        {
            // Roslyn's #r directive parser reads the path as a raw file-system string between
            // the outer double-quotes — it does NOT process C# escape sequences and does NOT
            // accept verbatim @"…" syntax. Backslashes are therefore emitted as-is (they are
            // literal in the #r path grammar, not escape characters). The only character we
            // cannot safely embed is `"` itself; in practice Windows paths never contain one
            // so this guard is purely defensive.
            sb.Append("#r \"");
            foreach (char c in path)
            {
                if (c != '"') sb.Append(c);
            }

            sb.Append("\"\n");
        }

        sb.Append('\n');
    }

    private static void EmitUsings(StringBuilder sb)
    {
        sb.Append("using System;\n");
        sb.Append("using System.Threading.Tasks;\n");
        sb.Append("using EnvDTE;\n");
        sb.Append("using EnvDTE80;\n");
        sb.Append("using Community.VisualStudio.Toolkit;\n");
        sb.Append("using Macros.Engine.Scripting;\n");
        sb.Append("using Macros.Engine.Triggers;\n");
        sb.Append("using static Macros.Engine.Scripting.Helpers;\n");
        sb.Append("using static Community.VisualStudio.Toolkit.VS;\n");
        sb.Append('\n');
    }

    private static void EmitGlobalStubs(StringBuilder sb)
    {
        sb.Append("// Editor-only stubs for script globals (MacroGlobals shape).\n");
        sb.Append("// At runtime these are never seen — the player swaps in a SourceReferenceResolver\n");
        sb.Append("// that returns empty source for this file.\n");
        sb.Append("EnvDTE80.DTE2 DTE = null!;\n");
        sb.Append("Macros.Engine.Scripting.IMacroContext Context = null!;\n");
        sb.Append("Macros.Engine.Triggers.IMacroTrigger Trigger = null!;\n");
    }
}
