using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Macros.Engine.Recording;

namespace Macros.Engine.Codegen;

/// <summary>
/// Pure transform from a captured <see cref="RecordedStep"/> sequence to a
/// human-readable, directly-executable <c>.csx</c> source string.
/// </summary>
/// <remarks>
/// <para>
/// <b>Pure.</b> No I/O, no statics, no clock — the caller passes <paramref
/// name="utcNow"/> so snapshot tests are deterministic. Output is a plain
/// <see cref="string"/>; persistence is the storage layer's job.
/// </para>
/// <para>
/// <b>Output contract.</b> The emitted script:
/// (1) opens with a UTC ISO-8601 header block including step count and a
///     "Generated by Macros — edit freely." line so users editing in VS know what
///     they're looking at;
/// (2) emits a <c>#load</c> directive for the IntelliSense shim
///     (<c>.intellisense/Macros.Intellisense.csx</c>) so the C# editor resolves
///     EnvDTE/EnvDTE80, the Community Toolkit's <c>VS</c> facade, Macros Helpers,
///     and script globals (<c>DTE</c>, <c>Context</c>, <c>Trigger</c>). The
///     relative path is identical for both global and repo macro stores. The shim
///     is the single source of truth for assembly references in the editor;
///     <see cref="Player.MacroPlayer"/> intercepts this directive via a custom
///     <c>SourceReferenceResolver</c> and returns an empty stream, so shim stubs
///     never shadow the real <c>MacroGlobals</c> at runtime. Standard <c>using</c>
///     directives are provided by the shim's <c>#load</c> and by
///     <see cref="Player.MacroPlayer"/>'s <c>ScriptOptions.WithImports</c>, so the
///     macro file itself needs none;
/// (3) emits one helper call per step; the source of each step's <see cref="RecordedStep"/>
///     subtype is implicit in the helper name (<c>OpenFileAsync</c>, <c>TypeAsync</c>, …).
///     <em>No</em> per-step <c>// step N</c> comment is emitted — they added noise without
///     adding value; users editing macros only care about the actual code.
/// </para>
/// <para>
/// <b>Line endings.</b> All emitted line breaks are bare <c>\n</c>. Roslyn's
/// script parser is line-ending-agnostic, but normalised output keeps golden-file
/// comparisons deterministic across Windows / Unix without requiring callers to
/// configure <c>core.autocrlf</c> for the test data.
/// </para>
/// </remarks>
public static class CSharpCodeGenerator
{
    private const string IntelliSenseLoadDirective = "#load \".intellisense/Macros.Intellisense.csx\"";

    private const string TodoDeletion =
        "TODO(m4-deletion-replay): deletion replay not yet supported; replaying via raw Edit.Delete which deletes the current selection, not the recorded range.";

    // A DTE command name is a dot-separated identifier sequence (e.g. "Edit.Copy",
    // "View.SolutionExplorer", "Build.BuildSelection"). When the recorder fails to
    // resolve a friendly name it leaves Name = null; when it surfaces a non-null
    // value that doesn't match this shape (e.g. raw localised strings, internal
    // markers) we fall back to the GUID/ID dispatch so the replay can't go through
    // DTE.ExecuteCommand with a name DTE can't parse.
    private static readonly Regex DteNameRegex = new(
        @"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    /// <summary>
    /// Generates a complete <c>.csx</c> source string for the supplied captured steps.
    /// </summary>
    /// <param name="steps">The ordered sequence of recorded steps. May be empty.</param>
    /// <param name="macroName">The macro's display name; included verbatim in the header comment.</param>
    /// <param name="utcNow">The UTC timestamp to embed in the header. Caller-supplied for testability.</param>
    /// <returns>A C#-script source string that <see cref="Player.MacroPlayer"/> can compile and run.</returns>
    /// <remarks>
    /// Steps that the generator cannot render readable code for (e.g. captured commands with no
    /// DTE-resolved friendly name) are silently dropped — the resulting <c>.csx</c> is the canonical,
    /// human-editable form, not a faithful replay of every captured event.
    /// </remarks>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="steps"/> or <paramref name="macroName"/> is <see langword="null"/>.
    /// </exception>
    public static string Generate(IReadOnlyList<RecordedStep> steps, string macroName, DateTime utcNow)
    {
        if (steps is null) throw new ArgumentNullException(nameof(steps));
        if (macroName is null) throw new ArgumentNullException(nameof(macroName));

        // Drop steps the codegen can't render in human-readable form (e.g. commands with no
        // DTE-resolved friendly name). These would otherwise produce ugly Guid+id fallbacks
        // that confuse the user and aren't usefully replayable as authored code.
        var emittable = new List<RecordedStep>(steps.Count);
        for (int i = 0; i < steps.Count; i++)
        {
            if (IsEmittable(steps[i])) emittable.Add(steps[i]);
        }

        var sb = new StringBuilder(capacity: 512 + (emittable.Count * 64));
        EmitHeader(sb, macroName, emittable.Count, utcNow);
        EmitReferenceDirectives(sb);

        for (int i = 0; i < emittable.Count; i++)
        {
            EmitStep(sb, emittable[i]);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a new-user scaffold for an empty macro with the standard header and
    /// IntelliSense shim, but no recorded steps.
    /// </summary>
    public static string GenerateEmpty(string macroName, DateTime utcNow)
    {
        if (macroName is null) throw new ArgumentNullException(nameof(macroName));

        var sb = new StringBuilder(capacity: 512);
        EmitHeader(sb, macroName, stepCount: 0, utcNow);
        EmitReferenceDirectives(sb);
        sb.Append("// Your code here\n");
        return sb.ToString();
    }

    private static bool IsEmittable(RecordedStep step) =>
        step switch
        {
            RecordedStep.CommandStep cmd =>
                !string.IsNullOrWhiteSpace(cmd.Name) && DteNameRegex.IsMatch(cmd.Name!),
            _ => true,
        };

    private static void EmitHeader(StringBuilder sb, string macroName, int stepCount, DateTime utcNow)
    {
        // Always normalise to UTC; ISO-8601 with second precision keeps headers
        // diffable in source control without flooding the file with millis.
        var iso = utcNow.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture);
        sb.Append("// Macro: ").Append(macroName).Append('\n');
        sb.Append("// Recorded: ").Append(iso).Append('\n');
        sb.Append("// Generated by Macros — edit freely.\n");
        sb.Append("// Documentation: https://github.com/madskristensen/Macros/tree/master/docs\n");
        sb.Append('\n');
    }

    private static void EmitReferenceDirectives(StringBuilder sb)
    {
        sb.Append("// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).\n");
        sb.Append(IntelliSenseLoadDirective).Append('\n');
        sb.Append("using Community.VisualStudio.Toolkit;\n");
        sb.Append("using static Macros.Engine.Scripting.Helpers;\n");
        sb.Append('\n');
    }

    private static void EmitStep(StringBuilder sb, RecordedStep step)
    {
        switch (step)
        {
            case RecordedStep.CommandStep cmd:
                EmitCommandStep(sb, cmd);
                break;
            case RecordedStep.FileOpenStep fileOpen:
                EmitFileOpenStep(sb, fileOpen);
                break;
            case RecordedStep.FileCloseStep fileClose:
                EmitFileCloseStep(sb, fileClose);
                break;
            case RecordedStep.ToolWindowClosedStep twClose:
                EmitToolWindowClosedStep(sb, twClose);
                break;
            case TextEditStep edit:
                EmitTextEditStep(sb, edit);
                break;
            default:
                // Defensive: a future RecordedStep subtype that lands before this
                // generator is updated still produces parseable output rather than
                // throwing at codegen time and stranding the user's recording.
                sb.Append("// unknown step kind ")
                  .Append(step.GetType().Name)
                  .Append(" (skipped — generator needs an update)\n");
                break;
        }
    }

    private static void EmitFileOpenStep(StringBuilder sb, RecordedStep.FileOpenStep step)
    {
        sb.Append("await OpenFileAsync(").Append(QuoteVerbatim(step.Path)).Append(");\n");
    }

    private static void EmitFileCloseStep(StringBuilder sb, RecordedStep.FileCloseStep step)
    {
        sb.Append("await CloseFileAsync(").Append(QuoteVerbatim(step.Path)).Append(");\n");
    }

    private static void EmitToolWindowClosedStep(StringBuilder sb, RecordedStep.ToolWindowClosedStep step)
    {
        sb.Append("await CloseToolWindowAsync(").Append(QuoteRegular(step.Caption)).Append(");\n");
    }

    private static void EmitCommandStep(StringBuilder sb, RecordedStep.CommandStep cmd)
    {
        // Generate() pre-filters via IsEmittable — Name is guaranteed non-null and regex-matched here.
        if (string.IsNullOrWhiteSpace(cmd.Name) || !DteNameRegex.IsMatch(cmd.Name!))
        {
            throw new InvalidOperationException(
                $"EmitCommandStep called with un-emittable command (Name={cmd.Name ?? "<null>"}). " +
                "IsEmittable should have filtered this step out.");
        }

        sb.Append("await ExecuteCommandAsync(").Append(QuoteRegular(cmd.Name!)).Append(");\n");
    }

    private static void EmitTextEditStep(StringBuilder sb, TextEditStep edit)
    {
        bool hasInsert = !string.IsNullOrEmpty(edit.NewText);
        bool hasDelete = edit.OldLength > 0;

        if (!hasInsert && !hasDelete)
        {
            // OldLength==0 AND NewText=="" should never escape the aggregator, but emit
            // nothing rather than silently dropping the step so a recorder bug becomes
            // visible as an unexplained "skipped" entry rather than a mysterious off-by-one
            // in playback.
            sb.Append("// (no-op text edit skipped)\n");
            return;
        }

        if (hasInsert && !hasDelete)
        {
            sb.Append("await TypeAsync(").Append(Quote(edit.NewText)).Append(");\n");
            return;
        }

        if (hasDelete && !hasInsert)
        {
            sb.Append("// ").Append(TodoDeletion).Append('\n');
            sb.Append("await ExecuteCommandAsync(\"Edit.Delete\");\n");
            return;
        }

        // Replacement: emit deletion preamble + insertion. m4-deletion-replay will
        // teach the generator to map (pos, length) back to (line, col) ranges and
        // emit SelectAsync(...) + Edit.Delete + TypeAsync(...) so this becomes
        // semantically faithful instead of "delete current selection".
        sb.Append("// ").Append(TodoDeletion).Append('\n');
        sb.Append("await ExecuteCommandAsync(\"Edit.Delete\");\n");
        sb.Append("await TypeAsync(").Append(Quote(edit.NewText)).Append(");\n");
    }

    /// <summary>
    /// Encodes a string literal: verbatim form (<c>@"…"</c>) when the text spans
    /// multiple lines, regular form otherwise. Internal so tests can exercise the
    /// escape rules without going through <see cref="Generate"/>.
    /// </summary>
    internal static string Quote(string text)
    {
        if (text is null) throw new ArgumentNullException(nameof(text));
        return ContainsNewline(text) ? QuoteVerbatim(text) : QuoteRegular(text);
    }

    private static bool ContainsNewline(string text)
    {
        for (int i = 0; i < text.Length; i++)
        {
            if (text[i] == '\n' || text[i] == '\r') return true;
        }

        return false;
    }

    internal static string QuoteRegular(string text)
    {
        if (text is null) throw new ArgumentNullException(nameof(text));

        var sb = new StringBuilder(text.Length + 2);
        sb.Append('"');
        for (int i = 0; i < text.Length; i++)
        {
            char c = text[i];
            switch (c)
            {
                case '\\': sb.Append(@"\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\0': sb.Append(@"\0"); break;
                case '\a': sb.Append(@"\a"); break;
                case '\b': sb.Append(@"\b"); break;
                case '\f': sb.Append(@"\f"); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                case '\t': sb.Append(@"\t"); break;
                case '\v': sb.Append(@"\v"); break;
                default:
                    if (c < 0x20 || (c >= 0x7F && c <= 0x9F))
                    {
                        sb.Append(@"\u").Append(((int)c).ToString("X4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    internal static string QuoteVerbatim(string text)
    {
        if (text is null) throw new ArgumentNullException(nameof(text));

        var sb = new StringBuilder(text.Length + 3);
        sb.Append("@\"");
        for (int i = 0; i < text.Length; i++)
        {
            char c = text[i];
            if (c == '"') sb.Append("\"\""); else sb.Append(c);
        }

        sb.Append('"');
        return sb.ToString();
    }
}
