using System;
using System.Collections.Generic;
using System.IO;

namespace Macros.Engine.Storage;

/// <summary>
/// One-time, idempotent migrator that injects the IntelliSense shim <c>#load</c> directive
/// into <c>.csx</c> macro files that were recorded before commit 12056f1 added the directive
/// to <see cref="Codegen.CSharpCodeGenerator"/>, and strips the now-redundant
/// <c>#r "EnvDTE"</c> / <c>#r "EnvDTE80"</c> block from any file that still carries it.
/// </summary>
/// <remarks>
/// <para>
/// <b>Problem.</b> Macros recorded with old codegen (pre-12056f1) lack the line
/// <c>#load ".intellisense/Macros.Intellisense.csx"</c>. Without it the C# editor never
/// reads the shim file, so EnvDTE/EnvDTE80, the Toolkit's <c>VS</c> facade, and the script
/// globals (<c>DTE</c>, <c>Context</c>, <c>Trigger</c>) are all unresolved red squiggles.
/// Additionally, codegen between commit 12056f1 and the current commit emitted redundant
/// <c>#r "EnvDTE"</c> and <c>#r "EnvDTE80"</c> directives — the shim's absolute-path
/// <c>#r</c> directives already cover these for the editor, and the runtime player adds them
/// via <c>ScriptOptions.WithReferences</c>.
/// </para>
/// <para>
/// <b>Fix.</b> <see cref="Migrate"/> scans the store root for <c>*.csx</c> files and for
/// each file: (a) injects the canonical 6-line shim <c>#load</c> block immediately before
/// the first non-comment, non-blank line if the shim reference is absent; (b) strips the
/// obsolete <c>#r "EnvDTE"</c> / <c>#r "EnvDTE80"</c> block if present.  The two operations
/// are independent and both are applied in a single atomic write when needed.
/// </para>
/// <para>
/// <b>Idempotent.</b> A file that already contains the shim reference and no obsolete
/// <c>#r</c> lines is left untouched. Calling <see cref="Migrate"/> twice is safe.
/// </para>
/// <para>
/// <b>Atomic write.</b> Modified content is written to a uniquely-named sibling <c>.tmp</c>
/// file first, then swapped into place via <see cref="File.Replace(string,string,string)"/>
/// when the destination exists, or <see cref="File.Move(string,string)"/> when it doesn't.
/// A crash mid-write leaves the previous file intact and at worst leaves a stray <c>.tmp</c>
/// behind.
/// </para>
/// <para>
/// <b>Thread-safety.</b> The class holds no instance or static mutable state. All operations
/// are local path computations and standard file-system calls, so it is safe to call
/// concurrently from multiple threads (each call operates on independent file paths).
/// </para>
/// </remarks>
public static class MacroFileLoadDirectiveMigrator
{
    // The shim file name — same value as IntelliSenseShimWriter.ShimFileName.
    // Kept local to avoid a cross-namespace compile dependency.
    private const string ShimFileName = "Macros.Intellisense.csx";

    // Substring we look for when deciding whether a file already references the shim.
    // Case-insensitive comparison is applied at the call site.
    private const string ShimFileNameSubstring = "Macros.Intellisense.csx";

    // The exact block that CSharpCodeGenerator.EmitReferenceDirectives now emits.
    // Each entry is ONE line WITHOUT a trailing line-ending;
    // line endings are appended by InjectShimBlock using the file's own detected style.
    private static readonly string[] ShimBlock =
    [
        "// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).",
        "#load \".intellisense/Macros.Intellisense.csx\"",
        "using EnvDTE;",
        "using EnvDTE80;",
        "using Community.VisualStudio.Toolkit;",
        "using Macros.Engine.Scripting;",
        "using Macros.Engine.Triggers;",
        "using static Macros.Engine.Scripting.Helpers;",
        "using static Community.VisualStudio.Toolkit.VS;",
        "",   // blank line terminating the shim block
    ];

    // The standard `using` lines that must appear in every macro file for IntelliSense.
    // VS's scripting IntelliSense does NOT propagate `using` directives from #load'ed files.
    private static readonly string[] RequiredUsingLines =
    [
        "using EnvDTE;",
        "using EnvDTE80;",
        "using Community.VisualStudio.Toolkit;",
        "using Macros.Engine.Scripting;",
        "using Macros.Engine.Triggers;",
        "using static Macros.Engine.Scripting.Helpers;",
        "using static Community.VisualStudio.Toolkit.VS;",
    ];

    // The `// Source format:` line emitted by older codegen builds.
    private const string SourceFormatLine =
        "// Source format: C# Script (.csx) \u2014 executed by Macros.Engine.Player.MacroPlayer.";

    // The 4-line verbose shim comment block emitted by codegen between the shim-injection
    // commit and this slim-header change.  The first line is used as a fast-detect sentinel.
    private static readonly string[] VerboseShimCommentLines =
    [
        "// #load below pulls in the IntelliSense shim (auto-generated by the Macros VSIX)",
        "// so the C# editor can resolve EnvDTE/EnvDTE80, the Toolkit's VS facade,",
        "// the Macros Helpers, and script globals (DTE, Context, Trigger). The runtime",
        "// player ignores this #load via a custom SourceReferenceResolver.",
    ];

    private const string NewShimCommentLine =
        "// IntelliSense + script globals come from this shim (auto-generated by the Macros VSIX).";

    /// <summary>
    /// Recursively scans <paramref name="storeRoot"/> for <c>*.csx</c> macro files and
    /// injects the IntelliSense shim <c>#load</c> directive into any file that lacks it.
    /// </summary>
    /// <remarks>
    /// The <c>.intellisense\</c> subdirectory (any casing) is excluded from scanning so
    /// the auto-generated shim is never modified. The global store keeps named macros under
    /// a subfolder (<c>&lt;root&gt;\Macros\&lt;name&gt;.csx</c>); recursive scanning ensures
    /// both layouts (global and repo) are covered without the caller having to special-case
    /// the global named subfolder.
    /// </remarks>
    /// <param name="storeRoot">
    /// Absolute path to the macro store root (e.g. <c>%APPDATA%\Macros</c> or
    /// <c>&lt;solutionDir&gt;\.vs\Macros</c>). Must not be <see langword="null"/>, empty,
    /// or whitespace.
    /// </param>
    /// <returns>
    /// A <see cref="MigrationResult"/> summarising how many files were scanned, updated,
    /// skipped, and how many per-file errors were encountered. Files inside
    /// <c>.intellisense\</c> are not counted in <c>Scanned</c>.
    /// </returns>
    /// <exception cref="ArgumentException">
    /// <paramref name="storeRoot"/> is <see langword="null"/>, empty, or whitespace.
    /// </exception>
    public static MigrationResult Migrate(string storeRoot)
    {
        if (string.IsNullOrWhiteSpace(storeRoot))
        {
            throw new ArgumentException("Store root must be a non-empty path.", nameof(storeRoot));
        }

        if (!Directory.Exists(storeRoot))
        {
            return new MigrationResult(0, 0, 0, Array.Empty<string>());
        }

        int scanned = 0;
        int updated = 0;
        int skipped = 0;
        var errors = new List<string>();

        foreach (string filePath in Directory.EnumerateFiles(storeRoot, "*.csx", SearchOption.AllDirectories))
        {
            // Files inside the .intellisense\ folder are never counted or modified.
            if (IsInIntelliSenseFolder(filePath))
            {
                continue;
            }

            scanned++;
            string fileName = Path.GetFileName(filePath);

            // Belt-and-suspenders: skip the shim file even if it somehow ends up outside
            // the .intellisense\ folder (e.g., a user-dropped copy in the store root).
            if (string.Equals(fileName, ShimFileName, StringComparison.OrdinalIgnoreCase))
            {
                skipped++;
                continue;
            }

            try
            {
                string content = File.ReadAllText(filePath);

                bool hasShim           = content.IndexOf(ShimFileNameSubstring, StringComparison.OrdinalIgnoreCase) >= 0;
                bool hasObsoleteR      = HasObsoleteEnvDTEDirectives(content);
                bool hasSourceFormat   = HasSourceFormatLine(content);
                bool hasVerboseShim    = HasVerboseShimComment(content);
                bool hasAllUsings      = HasAllRequiredUsings(content);

                // Nothing to do: shim already present with usings, no obsolete constructs.
                if (hasShim && hasAllUsings && !hasObsoleteR && !hasSourceFormat && !hasVerboseShim)
                {
                    skipped++;
                    continue;
                }

                // Strip obsolete #r block first so FindBodyStart lands on the using
                // block rather than the #r lines when the shim must also be injected.
                string migrated = content;
                if (hasObsoleteR)
                {
                    migrated = StripObsoleteEnvDTEDirectives(migrated);
                }

                if (hasSourceFormat)
                {
                    migrated = StripSourceFormatLine(migrated);
                }

                if (hasVerboseShim)
                {
                    migrated = ReplaceVerboseShimComment(migrated);
                }

                if (!hasShim)
                {
                    // Full injection: shim block includes #load + usings.
                    // Strip any pre-existing standard usings to avoid duplicates.
                    migrated = StripStandardUsings(migrated);
                    migrated = InjectShimBlock(migrated);
                }
                else if (!hasAllUsings)
                {
                    // Shim exists but usings are missing (stripped by prior migration).
                    // Inject them after the #load line.
                    migrated = InjectUsingsAfterLoad(migrated);
                }

                WriteAtomic(filePath, migrated);
                updated++;
            }
            catch (Exception ex)
            {
                errors.Add($"{fileName}: {ex.Message}");
            }
        }

        return new MigrationResult(scanned, updated, skipped, errors);
    }

    // ── private helpers ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="filePath"/> is located inside a
    /// directory segment that is exactly <c>.intellisense</c> (case-insensitive). Segment
    /// equality — not substring — is used so a file whose <em>name</em> contains
    /// <c>.intellisense</c> (e.g., <c>my.intellisense.csx</c>) is not affected.
    /// </summary>
    private static bool IsInIntelliSenseFolder(string filePath)
    {
        string[] segments = filePath.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        // The last segment is the file name — only directory segments can match.
        for (int i = 0; i < segments.Length - 1; i++)
        {
            if (string.Equals(segments[i], ".intellisense", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Returns a copy of <paramref name="content"/> with the IntelliSense shim block
    /// inserted immediately before the first line that is neither a <c>//</c> comment
    /// nor blank (i.e., before the first executable directive or code line).
    /// </summary>
    internal static string InjectShimBlock(string content)
    {
        string nl = DetectLineEnding(content);

        // Split preserving the trailing empty segment so a trailing newline round-trips.
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);

        int bodyStart = FindBodyStart(lines);

        var result = new System.Text.StringBuilder(content.Length + 256);

        for (int i = 0; i < bodyStart; i++)
        {
            result.Append(lines[i]);
            result.Append(nl);
        }

        foreach (string shimLine in ShimBlock)
        {
            result.Append(shimLine);
            result.Append(nl);
        }

        for (int i = bodyStart; i < lines.Length; i++)
        {
            result.Append(lines[i]);
            if (i < lines.Length - 1)
            {
                result.Append(nl);
            }
        }

        return result.ToString();
    }

    /// <summary>
    /// Returns the index of the first line that is neither a <c>//</c> comment nor an
    /// empty/whitespace-only line. Returns <paramref name="lines"/>.<c>.Length</c> when
    /// every line in the file is a comment or blank.
    /// </summary>
    internal static int FindBodyStart(string[] lines)
    {
        for (int i = 0; i < lines.Length; i++)
        {
            string trimmed = lines[i].Trim();
            if (trimmed.Length == 0) continue;       // blank
            if (trimmed.StartsWith("//")) continue;  // comment
            return i;
        }

        return lines.Length;
    }

    /// <summary>
    /// Detects the line-ending convention by inspecting the first newline in
    /// <paramref name="content"/>. Defaults to <c>\n</c> (matching codegen output) when
    /// no newline is found.
    /// </summary>
    internal static string DetectLineEnding(string content)
    {
        for (int i = 0; i < content.Length; i++)
        {
            if (content[i] == '\r' && i + 1 < content.Length && content[i + 1] == '\n')
            {
                return "\r\n";
            }

            if (content[i] == '\n')
            {
                return "\n";
            }
        }

        return "\n";
    }

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="content"/> contains the obsolete
    /// <c>#r "EnvDTE"</c> + <c>#r "EnvDTE80"</c> consecutive-line pattern.
    /// </summary>
    private static bool HasObsoleteEnvDTEDirectives(string content)
    {
        string nl = DetectLineEnding(content);
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);
        for (int i = 0; i < lines.Length - 1; i++)
        {
            if (lines[i].Trim() == "#r \"EnvDTE\"" &&
                lines[i + 1].Trim() == "#r \"EnvDTE80\"")
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Returns a copy of <paramref name="content"/> with the obsolete
    /// <c>#r "EnvDTE"</c> / <c>#r "EnvDTE80"</c> block removed.
    /// </summary>
    /// <remarks>
    /// <para>
    /// If the two lines immediately preceding <c>#r "EnvDTE"</c> are both <c>//</c>
    /// comments AND one of them contains the text <c>#r directives</c>, the entire
    /// 4-line block (2 comment lines + 2 <c>#r</c> lines) is removed.  Otherwise only
    /// the two <c>#r</c> lines are removed and surrounding comments are left alone
    /// (defensive: handles the case where a <c>// @trigger</c> line or other comment
    /// sits between the generated comment block and the <c>#r</c> lines).
    /// </para>
    /// <para>
    /// After removal, any pair of consecutive blank lines produced by the operation is
    /// collapsed to a single blank line so the file does not accumulate extra whitespace
    /// on repeated migration passes.
    /// </para>
    /// </remarks>
    internal static string StripObsoleteEnvDTEDirectives(string content)
    {
        string nl = DetectLineEnding(content);
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);

        // Find the first consecutive (#r "EnvDTE", #r "EnvDTE80") pair.
        int envDteIdx = -1;
        for (int i = 0; i < lines.Length - 1; i++)
        {
            if (lines[i].Trim() == "#r \"EnvDTE\"" &&
                lines[i + 1].Trim() == "#r \"EnvDTE80\"")
            {
                envDteIdx = i;
                break;
            }
        }

        if (envDteIdx < 0)
        {
            return content;
        }

        // Decide whether to strip 4 lines (comment block + #r lines) or only 2 (#r lines).
        int blockStart = envDteIdx;
        if (envDteIdx >= 2)
        {
            string prev1 = lines[envDteIdx - 1];
            string prev2 = lines[envDteIdx - 2];
            bool bothComments = prev1.TrimStart().StartsWith("//") &&
                                prev2.TrimStart().StartsWith("//");
            bool oneIsRDirectivesComment = prev1.Contains("#r directives") ||
                                           prev2.Contains("#r directives");
            if (bothComments && oneIsRDirectivesComment)
            {
                blockStart = envDteIdx - 2;
            }
        }

        int blockEnd = envDteIdx + 1; // inclusive index of #r "EnvDTE80"

        // Build result list, skipping the removed block.
        var stripped = new List<string>(lines.Length);
        for (int i = 0; i < lines.Length; i++)
        {
            if (i >= blockStart && i <= blockEnd)
            {
                continue;
            }

            stripped.Add(lines[i]);
        }

        // Collapse any consecutive blank lines introduced by the removal.
        // The final element (empty string from a trailing newline) is always kept.
        var collapsed = new List<string>(stripped.Count);
        bool prevBlank = false;
        for (int i = 0; i < stripped.Count; i++)
        {
            bool isBlank = stripped[i].Trim().Length == 0;
            bool isLast  = i == stripped.Count - 1;

            if (isBlank && prevBlank && !isLast)
            {
                continue; // skip the extra consecutive blank
            }

            collapsed.Add(stripped[i]);
            prevBlank = isBlank && !isLast;
        }

        // Reconstruct — no trailing nl after the last element (mirrors InjectShimBlock).
        var sb = new System.Text.StringBuilder(content.Length);
        for (int i = 0; i < collapsed.Count; i++)
        {
            sb.Append(collapsed[i]);
            if (i < collapsed.Count - 1)
            {
                sb.Append(nl);
            }
        }

        return sb.ToString();
    }

    private static bool HasSourceFormatLine(string content) =>
        content.IndexOf(SourceFormatLine, StringComparison.Ordinal) >= 0;

    private static bool HasVerboseShimComment(string content) =>
        content.IndexOf(VerboseShimCommentLines[0], StringComparison.Ordinal) >= 0;

    /// <summary>
    /// Returns <see langword="true"/> when ALL required using directives are present in <paramref name="content"/>.
    /// </summary>
    private static bool HasAllRequiredUsings(string content)
    {
        foreach (string u in RequiredUsingLines)
        {
            if (content.IndexOf(u, StringComparison.Ordinal) < 0) return false;
        }

        return true;
    }

    /// <summary>
    /// Injects the required <c>using</c> directives immediately after the <c>#load</c> line.
    /// Used when the shim <c>#load</c> already exists but usings were stripped by a prior migration.
    /// </summary>
    internal static string InjectUsingsAfterLoad(string content)
    {
        string nl = DetectLineEnding(content);
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);

        // Find the #load line
        int loadIndex = -1;
        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].TrimStart().StartsWith("#load") &&
                lines[i].IndexOf(ShimFileNameSubstring, StringComparison.OrdinalIgnoreCase) >= 0)
            {
                loadIndex = i;
                break;
            }
        }

        if (loadIndex < 0) return content; // shouldn't happen

        // Collect which usings are already present
        var existing = new HashSet<string>(StringComparer.Ordinal);
        foreach (string line in lines)
        {
            string trimmed = line.TrimEnd();
            if (trimmed.StartsWith("using "))
                existing.Add(trimmed);
        }

        // Build list of missing usings
        var missing = new List<string>();
        foreach (string u in RequiredUsingLines)
        {
            if (!existing.Contains(u))
                missing.Add(u);
        }

        if (missing.Count == 0) return content;

        // Insert missing usings right after the #load line
        var result = new System.Text.StringBuilder(content.Length + (missing.Count * 60));
        for (int i = 0; i <= loadIndex; i++)
        {
            result.Append(lines[i]);
            result.Append(nl);
        }

        foreach (string u in missing)
        {
            result.Append(u);
            result.Append(nl);
        }

        for (int i = loadIndex + 1; i < lines.Length; i++)
        {
            result.Append(lines[i]);
            if (i < lines.Length - 1)
            {
                result.Append(nl);
            }
        }

        return result.ToString();
    }

    /// <summary>
    /// Returns a copy of <paramref name="content"/> with the
    /// <c>// Source format: C# Script (.csx) …</c> line removed (exact match,
    /// trailing whitespace trimmed). Collapses any double-blank lines produced.
    /// </summary>
    internal static string StripSourceFormatLine(string content)
    {
        string nl = DetectLineEnding(content);
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);

        bool changed = false;
        var stripped = new List<string>(lines.Length);
        foreach (string line in lines)
        {
            if (line.TrimEnd() == SourceFormatLine)
            {
                changed = true;
            }
            else
            {
                stripped.Add(line);
            }
        }

        if (!changed) return content;

        var collapsed = CollapseBlankLines(stripped);
        return JoinLines(collapsed, nl);
    }

    /// <summary>
    /// Returns a copy of <paramref name="content"/> where the 4-line verbose shim
    /// comment block is replaced by the single canonical shim comment line.
    /// The <c>#load</c> line that immediately follows is preserved.
    /// </summary>
    internal static string ReplaceVerboseShimComment(string content)
    {
        string nl = DetectLineEnding(content);
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);

        int blockStart = -1;
        for (int i = 0; i <= lines.Length - VerboseShimCommentLines.Length; i++)
        {
            bool match = true;
            for (int j = 0; j < VerboseShimCommentLines.Length; j++)
            {
                if (lines[i + j].TrimEnd() != VerboseShimCommentLines[j])
                {
                    match = false;
                    break;
                }
            }

            if (match) { blockStart = i; break; }
        }

        if (blockStart < 0) return content;

        var result = new List<string>(lines.Length - VerboseShimCommentLines.Length + 1);
        for (int i = 0; i < lines.Length; i++)
        {
            if (i == blockStart)
            {
                result.Add(NewShimCommentLine);
                i += VerboseShimCommentLines.Length - 1;
            }
            else
            {
                result.Add(lines[i]);
            }
        }

        return JoinLines(result, nl);
    }

    /// <summary>
    /// Returns a copy of <paramref name="content"/> with the standard
    /// <c>using</c> directives that the old codegen emitted removed.
    /// Only the exact lines are matched (after trimming trailing whitespace).
    /// User-added <c>using</c> statements are never touched.
    /// Collapses any double-blank lines produced by the removal.
    /// </summary>
    /// <remarks>
    /// Retained for backward compatibility with tests. No longer called by <see cref="Migrate"/>.
    /// </remarks>
    internal static string StripStandardUsings(string content)
    {
        // Legacy set: the old codegen also emitted "using System;" and "using System.Threading.Tasks;"
        var legacyUsings = new HashSet<string>(StringComparer.Ordinal)
        {
            "using System;",
            "using System.Threading.Tasks;",
            "using EnvDTE;",
            "using EnvDTE80;",
            "using Community.VisualStudio.Toolkit;",
            "using Macros.Engine.Scripting;",
            "using static Macros.Engine.Scripting.Helpers;",
            "using static Community.VisualStudio.Toolkit.VS;",
        };

        string nl = DetectLineEnding(content);
        string[] lines = content.Split(new[] { nl }, StringSplitOptions.None);

        bool changed = false;
        var stripped = new List<string>(lines.Length);
        foreach (string line in lines)
        {
            if (legacyUsings.Contains(line.TrimEnd()))
            {
                changed = true;
            }
            else
            {
                stripped.Add(line);
            }
        }

        if (!changed) return content;

        var collapsed = CollapseBlankLines(stripped);
        return JoinLines(collapsed, nl);
    }

    /// <summary>
    /// Collapses runs of 2 or more consecutive blank lines to a single blank
    /// line. The trailing sentinel element (empty string produced by a file
    /// ending in a newline) is always preserved unchanged.
    /// </summary>
    private static List<string> CollapseBlankLines(List<string> lines)
    {
        var collapsed = new List<string>(lines.Count);
        bool prevBlank = false;
        for (int i = 0; i < lines.Count; i++)
        {
            bool isBlank = lines[i].Trim().Length == 0;
            bool isLast  = i == lines.Count - 1;

            if (isBlank && prevBlank && !isLast)
            {
                continue;
            }

            collapsed.Add(lines[i]);
            prevBlank = isBlank && !isLast;
        }

        return collapsed;
    }

    /// <summary>
    /// Reconstructs a string from <paramref name="lines"/> using <paramref name="nl"/>
    /// as the separator, without appending a trailing newline after the last element
    /// (mirrors the conventions used by <see cref="InjectShimBlock"/> and
    /// <see cref="StripObsoleteEnvDTEDirectives"/>).
    /// </summary>
    private static string JoinLines(List<string> lines, string nl)
    {
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < lines.Count; i++)
        {
            sb.Append(lines[i]);
            if (i < lines.Count - 1) sb.Append(nl);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Writes <paramref name="newContent"/> to <paramref name="destinationPath"/> atomically:
    /// writes to a uniquely-named sibling <c>.tmp</c> file first, then swaps into place via
    /// <see cref="File.Replace(string,string,string)"/> when the destination already exists,
    /// or <see cref="File.Move(string,string)"/> when it does not.
    /// </summary>
    private static void WriteAtomic(string destinationPath, string newContent)
    {
        string tmpPath = destinationPath + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllText(tmpPath, newContent);

            if (File.Exists(destinationPath))
            {
                File.Replace(tmpPath, destinationPath, destinationBackupFileName: null);
            }
            else
            {
                File.Move(tmpPath, destinationPath);
            }
        }
        catch
        {
            TryDeleteSilently(tmpPath);
            throw;
        }
    }

    private static void TryDeleteSilently(string path)
    {
        try
        {
            if (File.Exists(path)) File.Delete(path);
        }
        catch
        {
            // Best-effort cleanup — don't mask the original failure.
        }
    }
}

/// <summary>
/// Result returned by <see cref="MacroFileLoadDirectiveMigrator.Migrate"/>.
/// </summary>
/// <param name="Scanned">Total number of <c>.csx</c> files inspected.</param>
/// <param name="Updated">
/// Files that were modified — the shim <c>#load</c> was injected, the obsolete
/// <c>#r "EnvDTE"</c>/<c>#r "EnvDTE80"</c> block was stripped, or both.
/// </param>
/// <param name="Skipped">
/// Files left unchanged — either they already contained the shim <c>#load</c> reference, or
/// they are the shim file itself.
/// </param>
/// <param name="Errors">
/// Human-readable error lines for any per-file failures; never <see langword="null"/>.
/// Invariant: <c>Scanned == Updated + Skipped + Errors.Count</c>.
/// </param>
public sealed record MigrationResult(
    int Scanned,
    int Updated,
    int Skipped,
    IReadOnlyList<string> Errors);
